<?php

namespace lib\core;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-07-30 at 22:54:48.
 */
class ConfigTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Config
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 * @covers lib\core\Config::__construct
	 */
	protected function setUp() {
		$this->object = new Config();
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers lib\core\Config::get
	 * @covers lib\core\Config::loadConfigFile
	 */
	public function testGet() {
		$configFile = include SYS_PATH.'config/main.php';
		$dbConfigFIle = include SYS_PATH.'config/db.php';
		$this->assertEquals($configFile, $this->object->get());
		$this->assertEquals($configFile['log']['dev_mode'], $this->object->get('log.dev_mode'));
		$this->assertEquals($dbConfigFIle, $this->object->get('db'));
		$this->assertNull($this->object->get('no_such_config'));
	}
	
	/**
	 * Test for set values durning runtime
	 * @covers lib\core\Config::set
	 */
	public function testSet() {
		$this->object->set('new_config_node', 'this is value');
		$this->assertEquals('this is value', 
				$this->object->get('new_config_node'));
		
		$this->object->set('test.test1.value', 'this is value');
		$this->assertEquals('this is value', 
				$this->object->get('new_config_node'));
		
		$this->object->set(NULL, 'this is value');
		$this->assertEquals('this is value', 
				$this->object->get());
	}

}

/* EOF */